### ISSUE TITLE
How to use Gstreamer on RK3288 ?

### ISSUE THREAD

**Issue by pebauer68** [rockchip-linux/rockchip-va-driver#1]
I found two examples for usage of gstreamer pipelines and hardware en/decoding on RK3288 based MiQi SBC.
/usr/local/bin/test_enc.sh
/usr/local/bin/test_dec.sh
Is it possible to record the X11 screen on an RK3288 box with about 20 fps and 1920x1080 resolution to an mp4 movie via hardware-encoding ? How must the gst pipeline look like ?

test_enc.sh
#!/bin/sh
export DISPLAY=:0.0
echo "message: decoding raw video" > /tmp/video.log
#dump raw video
export LIBVA_DRIVER_NAME=vdpau
export VDPAU_DRIVER=rockchip
gst-launch-1.0 filesrc location=/usr/local/test.mp4 ! \
    qtdemux name=vdemux vdemux.video_0 ! queue ! vaapidecode ! queue ! \
    filesink location=/usr/local/output.yuv
echo "message: encoding" > /tmp/video.log

export LIBVA_DRIVER_NAME=rockchip
gst-launch-1.0 mp4mux name=mux ! \
    filesink location=/usr/local/output.mp4 \
    filesrc location=/usr/local/output.yuv ! \
    videoparse format=nv12 width=1920 height=1088 framerate=24 ! \
    vaapiencode_h264 ! queue ! mux. \
    filesrc location=/usr/local/test.mp4 ! \
    qtdemux name=demux demux.audio_0 ! decodebin ! voaacenc ! queue ! mux.

echo "message: playing encoded video" > /tmp/video.log

export LIBVA_DRIVER_NAME=vdpau
export VDPAU_DRIVER=rockchip
export OVERLAY=1
export OVERLAY_FULLSCREEN=1
gst-launch-1.0 $@ -v playbin uri=file:///usr/local/output.mp4
rm /tmp/video.log

test_dec.sh
#!/bin/sh
export DISPLAY=:0.0
export LIBVA_DRIVER_NAME=vdpau
export VDPAU_DRIVER=rockchip
export OVERLAY=1
export OVERLAY_FULLSCREEN=1

echo "message: playing video" > /tmp/video.log

#gst-launch-1.0 -m -v filesrc location=/usr/local/test.mp4 ! qtdemux ! vaapidecode ! vaapisink
#gst-launch-1.0 -m -v filesrc location=/usr/local/test.mp4 ! qtdemux ! vaapidecode ! vaapisink fullscreen=1
gst-launch-1.0 $@ -v playbin uri=file:///usr/local/test.mp4

rm /tmp/video.log

**Comment by hizukiayaka** [comment]
LIBVA_DRIVER_NAME=rockchip \
gst-launch-1.0  \
filesrc location=/home/linaro/1.mp4  \
! qtdemux !  vaapidecode ! vaapisink
works for me
