### ISSUE TITLE
ldconfig error

### ISSUE THREAD

**Issue by pebauer68** [rockchip-linux/rockchip-va-driver#2]
*so is not a symbolic link
What does this error tell the linux user ?
How can I solve this error ?
root@mq:/etc/network# ldconfig
/sbin/ldconfig.real: /usr/lib/arm-linux-gnueabihf/libgstvaapi-drm-1.2.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/arm-linux-gnueabihf/libgstcodecparsers_vpx.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/arm-linux-gnueabihf/libgstvaapi-wayland-1.2.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/arm-linux-gnueabihf/libgstvaapi-x11-1.2.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/arm-linux-gnueabihf/libgstvaapi-glx-1.2.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/arm-linux-gnueabihf/libgstvaapi-1.2.so.1 is not a symbolic link

root@mq:/etc/network# ls -l /usr/lib/arm-linux-gnueabihf/ | grep vaapi
-rwxr-xr-x 1 root root  2339998 Aug  3 11:30 libgstvaapi-1.2.so
-rwxr-xr-x 1 root root  2339998 Aug  3 11:30 libgstvaapi-1.2.so.1
-rwxr-xr-x 1 root root  2339998 Aug  3 11:30 libgstvaapi-1.2.so.1.0.0
lrwxrwxrwx 1 root root       24 Aug  7  2014 libgstvaapi-1.4.so.0 -> libgstvaapi-1.4.so.0.0.0
-rw-r--r-- 1 root root   371604 Aug  7  2014 libgstvaapi-1.4.so.0.0.0
-rwxr-xr-x 1 root root    59621 Aug  3 11:30 libgstvaapi-drm-1.2.so
-rwxr-xr-x 1 root root    59621 Aug  3 11:30 libgstvaapi-drm-1.2.so.1
-rwxr-xr-x 1 root root    59621 Aug  3 11:30 libgstvaapi-drm-1.2.so.1.0.0
lrwxrwxrwx 1 root root       28 Aug  7  2014 libgstvaapi-drm-1.4.so.0 -> libgstvaapi-drm-1.4.so.0.0.0
-rw-r--r-- 1 root root    13716 Aug  7  2014 libgstvaapi-drm-1.4.so.0.0.0
-rwxr-xr-x 1 root root   138040 Aug  3 11:30 libgstvaapi-glx-1.2.so
-rwxr-xr-x 1 root root   138040 Aug  3 11:30 libgstvaapi-glx-1.2.so.1
-rwxr-xr-x 1 root root   138040 Aug  3 11:30 libgstvaapi-glx-1.2.so.1.0.0
lrwxrwxrwx 1 root root       28 Aug  7  2014 libgstvaapi-glx-1.4.so.0 -> libgstvaapi-glx-1.4.so.0.0.0
-rw-r--r-- 1 root root    26296 Aug  7  2014 libgstvaapi-glx-1.4.so.0.0.0
-rwxr-xr-x 1 root root    92997 Aug  3 11:30 libgstvaapi-wayland-1.2.so
-rwxr-xr-x 1 root root    92997 Aug  3 11:30 libgstvaapi-wayland-1.2.so.1
-rwxr-xr-x 1 root root    92997 Aug  3 11:30 libgstvaapi-wayland-1.2.so.1.0.0
lrwxrwxrwx 1 root root       32 Aug  7  2014 libgstvaapi-wayland-1.4.so.0 -> libgstvaapi-wayland-1.4.so.0.0.0
-rw-r--r-- 1 root root    17968 Aug  7  2014 libgstvaapi-wayland-1.4.so.0.0.0
-rwxr-xr-x 1 root root   116431 Aug  3 11:30 libgstvaapi-x11-1.2.so
-rwxr-xr-x 1 root root   116431 Aug  3 11:30 libgstvaapi-x11-1.2.so.1
-rwxr-xr-x 1 root root   116431 Aug  3 11:30 libgstvaapi-x11-1.2.so.1.0.0
lrwxrwxrwx 1 root root       28 Aug  7  2014 libgstvaapi-x11-1.4.so.0 -> libgstvaapi-x11-1.4.so.0.0.0
-rw-r--r-- 1 root root    22080 Aug  7  2014 libgstvaapi-x11-1.4.so.0.0.0

**Comment by hizukiayaka** [comment]
The new build system is cmake, with the help of pkgconfig, it won't happen again.
