### ISSUE TITLE
Compatible problem

### ISSUE THREAD

**Issue by wzyy2** [rockchip-linux/rockchip-va-driver#3]
Hi randy,

Can you return VA_STATUS_SUCCESS in rockchip_QueryDisplayAttributes?
Otherwise, kodi will failed.

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp
`if (!CheckSuccess(vaQueryDisplayAttributes(m_display, m_attributes, &m_attributeCount)))
`

**Comment by wzyy2** [comment]
BTW,
Could you please pack this kodi branch as debian packages and push to rockchip-linux?

Thx
https://github.com/wzyy2/xbmc

**Comment by hizukiayaka** [comment]
OK, and I have just submitted a patch for it.
